"""
LIST ANALYSIS FUNCTIONS - COMPREHENSIVE GUIDE

This script demonstrates various built-in Python functions for analyzing lists.
Each section shows the input, output, and provides clear explanations.
"""

print("=" * 60)
print("PYTHON LIST ANALYSIS FUNCTIONS GUIDE")
print("=" * 60)
print()

print("SECTION 1: BASIC STATISTICAL FUNCTIONS")
print("-" * 40)
print("Input: number = [1,2,3,4,5,6,7,8,9,10,10]")
print()
print("max() function:")
print("- Finds the largest value in the list")
print("- Works with numbers, strings, and other comparable data types")
print()

print("min() function:")
print("- Finds the smallest value in the list") 
print("- Returns the minimum element")
print()

print("sum() function:")
print("- Adds up all numeric values in the list")
print("- Only works with numbers (int, float)")
print()

print("len() function:")
print("- Counts the total number of elements in the list")
print("- Includes duplicate values in the count")
print()

print("SECTION 2: BOOLEAN FUNCTIONS - all() and any()")
print("-" * 40)
print()
print("all() function:")
print("- Returns True if ALL elements are 'truthy' (not 0, False, None, or empty)")
print("- Returns False if ANY element is 'falsy'")
print("- Empty list returns True")
print()
print("Examples and their meanings:")
print("all([1,2,3,4,5]) → True (all numbers are non-zero)")
print("all([1,2,3,0,5]) → False (contains 0, which is falsy)")
print("all(['a','','b']) → False (empty string '' is falsy)")
print("all(['a',None,'b']) → False (None is falsy)")
print()

print("any() function:")
print("- Returns True if AT LEAST ONE element is 'truthy'")
print("- Returns False only if ALL elements are 'falsy'")
print("- Empty list returns False")
print()
print("Examples and their meanings:")
print("any([1,2,3,0,5]) → True (has truthy values like 1,2,3,5)")
print("any(['a','','b']) → True (has truthy values like 'a','b')")
print("any([None]) → False (None is falsy)")
print("any([0,0,0]) → False (all zeros are falsy)")
print()

print("SECTION 3: SEARCH AND COUNT FUNCTIONS")
print("-" * 40)
print()
print("count() method:")
print("- Counts how many times a specific value appears in the list")
print("- Returns 0 if the value is not found")
print()

print("index() method:")
print("- Finds the position (index) of the first occurrence of a value")
print("- Raises an error if the value is not found")
print("- List positions start from 0 (first element is at index 0)")
print()

print("SECTION 4: MEMBERSHIP TESTING")
print("-" * 40)
print()
print("'in' operator:")
print("- Checks if a value exists anywhere in the list")
print("- Returns True if found, False if not found")
print()
print("'not in' operator:")
print("- Opposite of 'in' - returns True if value is NOT in the list")
print("- Returns False if value is found")
print()

print("SECTION 5: LIST COMPARISON")
print("-" * 40)
print()
print("== operator (equality):")
print("- Compares if two lists have the same elements in the same order")
print("- Returns True if identical, False otherwise")
print()
print("< operator (less than):")
print("- Compares lists element by element (lexicographically)")
print("- For identical lists, returns False")
print()
print("'is' operator (identity):")
print("- Checks if two variables point to the exact same object in memory")
print("- Different from == which checks content")
print("- Two separate lists with same content are equal (==) but not identical (is)")
print()

print("EXPECTED OUTPUTS:")
print("-" * 40)
print("=" * 80)
print("📊 COMPREHENSIVE LIST ANALYSIS FUNCTIONS GUIDE")
print("=" * 80)
print("🎯 Learning how to analyze and explore lists with built-in Python functions")
print("💡 Each example shows INPUT → OUTPUT → EXPLANATION in simple terms")
print("=" * 80)

# Sample data for our examples
number = [1,2,3,4,5,6,7,8,9,10,10]
print(f"\n📋 Our sample list: {number}")
print("Notice: This list has 11 items, with the number 10 appearing twice")

print("\n" + "="*60)
print("1️⃣ FINDING MAXIMUM VALUE - max() function")
print("="*60)
print("📝 WHAT IT DOES: Finds the largest number in a list")
print("🔍 INPUT:", number)
max_number = max(number)
print("📤 OUTPUT:", max_number)
print("💬 EXPLANATION: Like looking through all your test scores and finding your highest score.")
print("   Python checks every number and remembers the biggest one it sees.")
print("   In our list, it compares 1, 2, 3... up to 10 and finds 10 is the largest.")

print("\n" + "="*60)  
print("2️⃣ FINDING MINIMUM VALUE - min() function")
print("="*60)
print("📝 WHAT IT DOES: Finds the smallest number in a list")
print("🔍 INPUT:", number)
min_number = min(number)
print("📤 OUTPUT:", min_number)
print("💬 EXPLANATION: Like finding the lowest temperature of the week.")
print("   Python looks at every number and keeps track of the smallest one.")
print("   In our list, it starts with 1 and since nothing is smaller, 1 is the minimum.")

print("\n" + "="*60)
print("3️⃣ CALCULATING TOTAL SUM - sum() function")  
print("="*60)
print("📝 WHAT IT DOES: Adds all numbers in a list together")
print("🔍 INPUT:", number)
total = sum(number)
print("📤 OUTPUT:", total)
print("💬 EXPLANATION: Like adding up all the money in your wallet.")
print("   Python takes each number and adds it to a running total:")
print("   1+2+3+4+5+6+7+8+9+10+10 = 65")
print("   This is useful for calculating averages, totals, etc.")

print("\n" + "="*60)
print("4️⃣ COUNTING ITEMS - len() function")
print("="*60)
print("📝 WHAT IT DOES: Counts how many items are in a list")
print("🔍 INPUT:", number)
len_number = len(number)
print("📤 OUTPUT:", len_number)
print("💬 EXPLANATION: Like counting how many books are on your shelf.")
print("   Python counts each position in the list, starting from 1.")
print("   Our list has 11 positions, even though 10 appears twice.")

print("\n" + "="*70)
print("5️⃣ CHECKING IF ALL ITEMS ARE TRUE - all() function")
print("="*70)
print("📝 WHAT IT DOES: Returns True only if ALL items in the list are 'truthy'")
print("💡 TRUTHY VALUES: Any number except 0, any text except empty string")
print("❌ FALSY VALUES: 0, empty string '', None, False")

print("\n🔍 EXAMPLE 1 - All positive numbers:")
test_list_1 = number
print("INPUT:", test_list_1)
result_1 = all(test_list_1)
print("OUTPUT:", result_1)
print("💬 EXPLANATION: All numbers (1,2,3...10) are truthy, so result is True")

print("\n🔍 EXAMPLE 2 - List with zero:")
test_list_2 = [1,2,3,0,5]
print("INPUT:", test_list_2)
result_2 = all(test_list_2)
print("OUTPUT:", result_2)
print("💬 EXPLANATION: Contains 0 (falsy), so result is False")
print("   It's like asking 'Are ALL students present?' - if one is absent, answer is No")

print("\n🔍 EXAMPLE 3 - Text with empty string:")
test_list_3 = ['a',"", 'b']
print("INPUT:", test_list_3)
result_3 = all(test_list_3)
print("OUTPUT:", result_3)
print("💬 EXPLANATION: Contains empty string '' (falsy), so result is False")

print("\n🔍 EXAMPLE 4 - Text with None:")
test_list_4 = ['a',None,'b']
print("INPUT:", test_list_4)
result_4 = all(test_list_4)
print("OUTPUT:", result_4)
print("💬 EXPLANATION: Contains None (falsy), so result is False")

print("\n" + "="*70)
print("6️⃣ CHECKING IF ANY ITEM IS TRUE - any() function")
print("="*70)
print("📝 WHAT IT DOES: Returns True if AT LEAST ONE item in the list is 'truthy'")

print("\n🔍 EXAMPLE 1 - Mixed numbers with zero:")
test_any_1 = [1,2,3,0,5]
print("INPUT:", test_any_1)
result_any_1 = any(test_any_1)
print("OUTPUT:", result_any_1)
print("💬 EXPLANATION: Has truthy numbers (1,2,3,5), so result is True")
print("   Like asking 'Is ANYONE here?' - if at least one person is present, answer is Yes")

print("\n🔍 EXAMPLE 2 - Text with empty string:")
test_any_2 = ['a',"", 'b']
print("INPUT:", test_any_2)
result_any_2 = any(test_any_2)
print("OUTPUT:", result_any_2)
print("💬 EXPLANATION: Has truthy strings ('a', 'b'), so result is True")

print("\n🔍 EXAMPLE 3 - Text with None:")
test_any_3 = ['a',None,'b']
print("INPUT:", test_any_3)
result_any_3 = any(test_any_3)
print("OUTPUT:", result_any_3)
print("💬 EXPLANATION: Has truthy strings ('a', 'b'), so result is True")

print("\n🔍 EXAMPLE 4 - Only None:")
test_any_4 = [None]
print("INPUT:", test_any_4)
result_any_4 = any(test_any_4)
print("OUTPUT:", result_any_4)
print("💬 EXPLANATION: Only contains None (falsy), so result is False")

print("\n🔍 EXAMPLE 5 - Only zeros:")
test_any_5 = [0,0,0]
print("INPUT:", test_any_5)
result_any_5 = any(test_any_5)
print("OUTPUT:", result_any_5)
print("💬 EXPLANATION: Only contains 0s (falsy), so result is False")

print("\n" + "="*60)
print("7️⃣ COUNTING OCCURRENCES - count() method")
print("="*60)
print("📝 WHAT IT DOES: Counts how many times a specific value appears")

print("\n🔍 EXAMPLE 1 - Counting the number 5:")
print("INPUT list:", number)
print("Looking for:", 5)
count_5 = number.count(5)
print("OUTPUT:", count_5)
print("💬 EXPLANATION: The number 5 appears exactly 1 time in our list")

print("\n🔍 EXAMPLE 2 - Counting the number 10:")
print("INPUT list:", number)
print("Looking for:", 10)
count_10 = number.count(10)
print("OUTPUT:", count_10)
print("💬 EXPLANATION: The number 10 appears 2 times in our list")
print("   This is useful for finding duplicates or frequency analysis")

print("\n" + "="*60)
print("8️⃣ FINDING POSITION - index() method")
print("="*60)
print("📝 WHAT IT DOES: Finds the position (index) of a value in the list")
print("💡 REMEMBER: Python starts counting positions from 0, not 1!")

print("\n🔍 FINDING INDEX OF NUMBER 7:")
print("INPUT list:", number)
print("Looking for:", 7)
index_of_7 = number.index(7)
print("OUTPUT:", index_of_7)
print("💬 EXPLANATION: Number 7 is at position 6 (counting from 0)")
print("   Position counting: 0,1,2,3,4,5,6,7,8,9,10")
print("   Values at those:  1,2,3,4,5,6,7,8,9,10,10")
print("   So 7 is at index 6")

print("\n" + "="*60)
print("9️⃣ MEMBERSHIP TESTING - 'in' and 'not in' operators")
print("="*60)
print("📝 WHAT IT DOES: Checks if a value exists in the list")

print("\n🔍 CHECKING IF 7 IS IN THE LIST:")
print("INPUT list:", number)
print("Checking for:", 7)
is_7_present = 7 in number
print("OUTPUT:", is_7_present)
print("💬 EXPLANATION: 7 exists in our list, so result is True")

print("\n🔍 CHECKING IF 15 IS IN THE LIST:")
print("INPUT list:", number)
print("Checking for:", 15)
is_15_present = 15 in number
print("OUTPUT:", is_15_present)
print("💬 EXPLANATION: 15 does not exist in our list, so result is False")

print("\n🔍 CHECKING IF 1 IS NOT IN THE LIST:")
print("INPUT list:", number)
print("Checking if 1 is NOT present:", end=" ")
is_1_not_present = 1 not in number
print("OUTPUT:", is_1_not_present)
print("💬 EXPLANATION: 1 IS in our list, so '1 not in list' is False")
print("   This is like asking 'Is 1 absent?' - since 1 is present, answer is False")

print("\n" + "="*60)
print("🔟 LIST COMPARISON OPERATIONS")
print("="*60)
print("📝 WHAT IT DOES: Compares two lists using different operators")

list1 = [1,2,3]
list2 = [1,2,3]
print(f"\nFor our examples:")
print(f"list1 = {list1}")
print(f"list2 = {list2}")

print("\n🔍 EQUALITY COMPARISON (==):")
print("INPUT: list1 == list2")
are_equal = list1 == list2
print("OUTPUT:", are_equal)
print("💬 EXPLANATION: Both lists have same values in same order, so they are equal")
print("   Like comparing two identical shopping lists")

print("\n🔍 LESS THAN COMPARISON (<):")
print("INPUT: list1 < list2")
is_less_than = list1 < list2
print("OUTPUT:", is_less_than)
print("💬 EXPLANATION: Since lists are identical, neither is 'less than' the other")
print("   Python compares element by element: 1=1, 2=2, 3=3, so result is False")

print("\n🔍 IDENTITY COMPARISON (is):")
print("INPUT: list1 is list2")
is_same_object = list1 is list2
print("OUTPUT:", is_same_object)
print("💬 EXPLANATION: Even though contents are same, they are different objects in memory")
print("   Like having two separate notebooks with identical content")
print("   == compares CONTENT, 'is' compares if they're the SAME OBJECT")

print("\n" + "="*80)
print("🎓 SUMMARY - WHEN TO USE EACH FUNCTION")
print("="*80)
print("📊 max()/min(): Finding highest/lowest values (grades, prices, temperatures)")
print("➕ sum(): Calculating totals (expenses, scores, quantities)")  
print("📏 len(): Counting items (inventory, students, files)")
print("✅ all(): Checking if everything meets a condition (all passed, all valid)")
print("🔍 any(): Checking if anything meets a condition (any errors, any matches)")
print("🔢 count(): Finding frequency (how often something occurs)")
print("📍 index(): Finding position (where is something located)")
print("🔎 in/not in: Checking existence (is item in stock, is user registered)")
print("⚖️ Comparisons: Sorting, filtering, validation")
print("="*80)